# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61i_service.proto\x12\x02\x61i\"0\n\x0cVideoRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x11\n\tfile_path\x18\x02 \x01(\t\"\\\n\nAIResponse\x12\r\n\x05route\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07objects\x18\x03 \x03(\t\x12\x0f\n\x07summary\x18\x04 \x01(\t\x12\x0c\n\x04\x66ile\x18\x05 \x01(\t2=\n\tAIService\x12\x30\n\x0cProcessVideo\x12\x10.ai.VideoRequest\x1a\x0e.ai.AIResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIDEOREQUEST']._serialized_start=24
  _globals['_VIDEOREQUEST']._serialized_end=72
  _globals['_AIRESPONSE']._serialized_start=74
  _globals['_AIRESPONSE']._serialized_end=166
  _globals['_AISERVICE']._serialized_start=168
  _globals['_AISERVICE']._serialized_end=229
# @@protoc_insertion_point(module_scope)
